title : nber1994
name: 'nber1994'
description: 'somebody someday sometime'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'BACK TO TOP'
  - url: 'https://github.com/nber1994'
    title: 'JUMP TO GITHUB'

collections:
  news:
    title: News
    default_open: false
    output: true
  posts:
    title: Essays
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: news
    values:
      title: News
      permalink: /news/:title

plugins:
  - jekyll-sitemap
